version: '3.3'

services:
  db:
    image : postgres:${DB_TAG}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  nginx:
    image: nginx:${NGINX_TAG}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

  api:
    image: ${DOCKER_USERNAME}/syzhet_fastapi:${API_TAG}
    restart: always
    env_file:
      - .env
    # ports:
    #   - ${APP__APP_PORT}:8000
    depends_on:
      - db
