version: '3.3'

services:
  db:
    image : postgres:${DB_TAG}
    restart: always
    # ports:
    #   - ${POSTGRES_PORT}:5432
    env_file:
      - .env

  nginx:
    image: nginx:${NGINX_TAG}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certbot
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - api

  api:
    image: ${DOCKER_USERNAME}/syzhet_fastapi:${API_TAG}
    restart: always
    env_file:
      - .env
    depends_on:
      - db
