version: '3.3'

services:
  syzdb:
    image : postgres:${DB_TAG}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    # volumes:
    #   - vkbot_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  # vknginx:
  #   image: nginx:1.19.3
  #   volumes:
  #     - ./images:/usr/share/nginx/html/
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   restart: always
  #   depends_on:
  #     - vkdb

  # vkbot:
  #   image: syzhet/coocking_vk_bot:latest
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - vknginx